### ISSUE TITLE
Standard testing image added to IPFS docker hub

### ISSUE THREAD

**Issue by ZenGround0** [ipfs/kubernetes-ipfs#30]
Presently the testing image in the cluster manifest (hsanjuan/ipfs-cluster:latest) is outdated, however there is no great alternative testing image to point people to for testing the latest release of ipfs-cluster.  I use zenground0/ipfs-cluster:official-test, but I frequently update this link with new images for testing not-yet-stable branches so linking others to it will likely lead to confusion.  Starting with the next release we should use ipfs/ipfs-cluster:test or something along those lines as an official up-to-date-with-release testing image.

**Comment by hsanjuan** [comment]
I'll add you to IPFS docker hub and you can configure a build for this image. whats your docker hub username?

**Comment by ZenGround0** [comment]
Thanks!  Username: zenground0

**Comment by hsanjuan** [comment]
@ZenGround0 added you
