### ISSUE TITLE
Add archives dataset to project

### ISSUE THREAD

**Issue by FrankPetrilli** [ipfs/kubernetes-ipfs#33]
I believed I had already committed these changes, but as it turns out, they remained on the cluster controller. Issue to track adding these files.

**Comment by hsanjuan** [comment]
Hello,

please make a PR to master so these are integrated after review.

Also, all tests in that commit are virtually identical except for a line number, which means they can be a single test correctly parametrized. Test language supports parameters now.

**Comment by ZenGround0** [comment]
@FrankPetrilli Feel free to ping me if you would like any help using new DSL features.

**Comment by FrankPetrilli** [comment]
See https://github.com/ipfs/kubernetes-ipfs/tree/archives_data for test; need to resolve bash dependency in vanilla container before I'll commit this.
